### ISSUE TITLE
Fails to Launch on wayland 

### ISSUE THREAD

**Issue by terroreek** [flathub/com.plexamp.Plexamp#95]
I am having an issue where plexamp on wayland fails to start on my desktop, I don't have this issue on my laptop which also has an AMD GPU

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --ozone-platform=wayland --enable-features=UseSkiaRenderer
[3:1207/185355.067338:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
LaunchProcess: failed to execvp:
xdg-settings
[3:1207/185355.249060:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/185355.249085:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Main: restoring window state from /home/terroreek/.var/app/com.plexamp.Plexamp/config/Plexamp/window-state-plexamp-main.json
Started Media Service: false
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
Linux: Registering MPRIS service.
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
libEGL warning: DRI2: failed to create dri screen
[51:1207/185355.302596:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
libEGL warning: DRI2: failed to create dri screen
[114:1207/185355.354969:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
amdgpu: unknown (family_id, chip_external_rev): (145, 1)
[60:1207/185355.394444:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[3:1207/185355.777736:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/185355.777758:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/185355.777779:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/185355.777791:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/185355.777802:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
Couldn't install shortcut for Command+Alt+Up.
Couldn't install shortcut for Command+Alt+Down.
Couldn't install shortcut for MediaPlayPause.
Couldn't install shortcut for MediaPreviousTrack.
Couldn't install shortcut for MediaNextTrack.
Couldn't install shortcut for MediaStop.
```
Running Siduction (Debian Sid)
Flatpak: 1.14.4-2
Kernel: 6.6.4-1-siduction-amd64 #1 SMP PREEMPT_DYNAMIC siduction 6.6-4 (2023-12-03) x86_64 GNU/Linux

Output from inxi -G
```
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] driver: amdgpu v: kernel
  Device-2: AMD Raphael driver: amdgpu v: kernel
  Device-3: Logitech BRIO Ultra HD Webcam
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB
  Device-4: Elgato Systems GmbH Cam Link 4K
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.2 with: Xwayland v: 23.2.2
    compositor: gnome-shell v: 44.5 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 3840x2160~120Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 vendor: amd mesa v: 23.2.1-1 renderer: AMD Radeon RX
    7900 XTX (gfx1100 LLVM 16.0.6 DRM 3.54 6.6.4-1-siduction-amd64)
  API: Vulkan v: 1.3.268 drivers: radv,llvmpipe surfaces: xcb,xlib,wayland
```

If I use flatseal and remove wayland permissions plexamp runs correctly.
